
name: "Check-Release"
description: Create a new release check.
title: "[RELEASE] - <title>"
labels: [
  "check"
]
body:
  - type: checkboxes
    attributes:
      label: Were contractual commitments respected ?
      description: Question about the contract
      options:
      - label: The contractual commitments were respected.
        required: true
  - type: checkboxes
    attributes:
      label: Was the delivery format respected ?
      description: Question about the delivery
      options:
      - label: The delivery format was respected.
        required: true
  - type: checkboxes
    attributes:
      label: Is the version identified and identifiable in the release artifact ?
      description: Question about the version
      options:
      - label: The release is identifiable by its version number.
        required: true
  - type: checkboxes
    attributes:
      label: Is there an available release note ?
      description: Question about the release note ?
      options:
      - label: The release note is available.
        required: true
